---

- name: provsision-jboss-eap-7.4
  hosts: all
  tasks:
  - name: download sources jboss-
    unarchive:
      src: "https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=99481"
      dest: "/tmp/"
      mode: 0755
  become: true

  