---

- name: provsision-jboss-eap-7.4
  hosts: all
  tasks:
  - name: Check if zip source file exists
    stat:
      path: "/tmp/jboss-eap-7.4.0.zip"
    register: register_name

  - name: download sources jboss
    get_url:
      url: "https://access.redhat.com/cspdownload/8e189a1338834573bf5db628c2dfaa2e/649d96fe/JBEAP-7.4.0/jboss-eap-7.4.0.zip"
      dest: "/tmp/jboss-eap-7.4.0.zip"
    when: not register_name.stat.exists

  - name: copy 
    ansible.builtin.template:
      src: test.xml
      dest: /tmp/
      
  become: true

  