---

- name: provsision-jboss-eap-7.4
  hosts: all
  tasks:
  - name: download sources jboss-
    unarchive:
      src: "https://developers.redhat.com/content-gateway/file/jboss-eap-7.4.0.zip"
      dest: "/tmp/"
      mode: 0755
      remote_src: yes
  become: true

  