---

#
# Setup/install tasks.
#

- include: provision-jdk.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - install-java

- include: provision-jboss-eap.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - install-jboss

